repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-ast
    - id: debug-statements
    - id: check-added-large-files

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
    - id: codespell
      exclude: >
          (?x)^(
              .*\.c
          )$
      args:
        - --ignore-words-list=nin,preformed,wih,
