name: Build and Deploy docs

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Create environment
      shell: bash -l {0}
      run: |
        conda create --name TEST python=3 python-build numpy --file requirements-dev.txt
        source activate TEST
        pip install -e . --no-deps --force-reinstall
        conda info --all
        conda list

    - name: Build documentation
      shell: bash -l {0}
      run: |
        source activate TEST
        set -e
        pushd docs
        make clean html linkcheck
        popd

    - name: GitHub Pages action
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
