name: Build and Deploy docs

on:
  pull_request:

  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install gsw
      run: >
        python -m pip install -r requirements-dev.txt
        && python -m pip install -e .

    - name: Build documentation
      run: >
        set -e
        && pushd docs
        && make clean html linkcheck
        && popd

    - name: GitHub Pages action
      if: success() && github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
