name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Micromamba 
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3.12 --file numpy requirements-dev.txt --channel conda-forge

    - name: Install gsw
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    # - name: Install nightly version of numpy
    #   run: |
    #     python -m pip install --pre --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple --extra-index-url https://pypi.org/simple numpy -U

    - name: Test Code Generation
      run: >
        git clone https://github.com/TEOS-10/GSW-C.git ../GSW-C
        && git clone https://github.com/TEOS-10/Matlab.git ../GSW-Matlab
        && python tools/copy_from_GSW-C.py
        && python tools/mat2npz.py
        && python tools/make_ufuncs.py
        && python tools/make_wrapped_ufuncs.py
        && python tools/fix_wrapped_ufunc_typos.py        
        && python -m pytest -s -rxs -v gsw/tests