name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [windows-latest, ubuntu-latest, macos-latest]
        # Oldest one based on NEP-29 and latest one.
        # See https://numpy.org/neps/nep-0029-deprecation_policy.html
        numpy-version: ["1.23", "1.26"]
        exclude:
          - python-version: "3.12"
            numpy-version: "1.23"
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup Micromamba Python ${{ matrix.python-version }} numpy ${{ matrix.numpy-version }}
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=${{ matrix.python-version }} python-build numpy=${{ matrix.numpy-version }} --file requirements-dev.txt --channel conda-forge

    - name: Install gsw
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Debug
      shell: bash -l {0}
      run: |
        python -c "import numpy; print(f'Running numpy {numpy.__version__}')"

    - name: Tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        pytest -s -rxs -v gsw/tests
