name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [windows-latest, ubuntu-latest, macos-latest]
        # Oldest one based on NEP-29 and latest one.
        # See https://numpy.org/neps/nep-0029-deprecation_policy.html
        numpy-version: ["1.19", "1.22"]
        exclude:
          - python-version: "3.10"
            numpy-version: "1.19"

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: false

    - name: Python ${{ matrix.python-version }} numpy ${{ matrix.numpy-version }}
      shell: bash -l {0}
      run: |
        micromamba create --name TEST python=${{ matrix.python-version }} python-build numpy=${{ matrix.numpy-version }} --file requirements-dev.txt --channel conda-forge
        micromamba activate TEST
        pip install -e . --no-deps --force-reinstall
        conda info --all
        conda list

    - name: Tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        python -c "import numpy; print(f'Running numpy {numpy.__version__}')"
        pytest -s -rxs -v gsw/tests
