name: Tests

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install gsw
      run: >
        python -m pip install -r requirements-dev.txt
        && python -m pip install -e .

    - name: Tests
      run: |
        python -m pytest -s -rxs -v gsw/tests
